name: Build and push Docker images

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: 0 16 * * 5

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Docker Login
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: limonchoms/tgbot-asf:latest
